#!/bin/bash
# Verification script for eth_simulateV1 local network setup

echo "====================================================================="
echo "eth_simulateV1 Local Network - Setup Verification"
echo "====================================================================="
echo ""

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

errors=0
warnings=0

# Check 1: Docker Compose file exists
echo "Check 1: Docker Compose configuration"
if [ -f "docker-compose.yml" ]; then
    echo "  ✓ docker-compose.yml exists"
else
    echo "  ✗ docker-compose.yml not found"
    errors=$((errors + 1))
fi

# Check 2: Configuration files
echo ""
echo "Check 2: Configuration files"
config_files=(
    "configs/ec-common/genesis.json"
    "configs/ec-common/config.toml"
    "configs/ec-common/jwtsecret.hex"
    "configs/consensus/config-lighthouse.yaml"
    "configs/consensus/config-prysm.yml"
    "configs/consensus/genesis.ssz"
    "configs/consensus/deposit-data.json"
)

for file in "${config_files[@]}"; do
    if [ -f "$file" ]; then
        echo "  ✓ $file"
    else
        echo "  ✗ $file not found"
        errors=$((errors + 1))
    fi
done

# Check 3: Scripts
echo ""
echo "Check 3: Scripts"
scripts=(
    "scripts/setup.sh"
    "scripts/start.sh"
    "scripts/stop.sh"
    "scripts/generate-genesis.sh"
    "scripts/health_check.py"
)

for script in "${scripts[@]}"; do
    if [ -f "$script" ]; then
        if [ -x "$script" ]; then
            echo "  ✓ $script (executable)"
        else
            echo "  ⚠ $script exists but not executable"
            warnings=$((warnings + 1))
        fi
    else
        echo "  ✗ $script not found"
        errors=$((errors + 1))
    fi
done

# Check 4: Tests
echo ""
echo "Check 4: Test files"
test_files=(
    "tests/test_eth_simulateV1.py"
    "tests/manual_test.py"
    "tests/README.md"
)

for file in "${test_files[@]}"; do
    if [ -f "$file" ]; then
        echo "  ✓ $file"
    else
        echo "  ✗ $file not found"
        errors=$((errors + 1))
    fi
done

# Check 5: Documentation
echo ""
echo "Check 5: Documentation"
doc_files=(
    "README.md"
    "QUICKSTART.md"
    "PROJECT_SUMMARY.md"
    "docs/test_report.md"
)

for file in "${doc_files[@]}"; do
    if [ -f "$file" ]; then
        echo "  ✓ $file"
    else
        echo "  ✗ $file not found"
        errors=$((errors + 1))
    fi
done

# Check 6: Docker services in compose file
echo ""
echo "Check 6: Docker services in docker-compose.yml"
services=("ec-opgeth" "ec-opreth" "cc-lighthouse" "cc-prysm" "validator-lighthouse" "test-runner")
for service in "${services[@]}"; do
    if grep -q "container_name: $service" docker-compose.yml; then
        echo "  ✓ Service $service defined"
    else
        echo "  ✗ Service $service not found in docker-compose.yml"
        errors=$((errors + 1))
    fi
done

# Check 7: P2P keys
echo ""
echo "Check 7: P2P keys"
for i in 1 2 3 4; do
    key_file="configs/ec-common/p2p-key-$i.hex"
    if [ -f "$key_file" ]; then
        echo "  ✓ $key_file"
    else
        echo "  ⚠ $key_file not found (will be generated if needed)"
        warnings=$((warnings + 1))
    fi
done

# Check 8: Validator keys
echo ""
echo "Check 8: Validator keys"
for i in 0 1 2 3; do
    key_dir="configs/consensus/validator-keys/validator_$i"
    if [ -d "$key_dir" ]; then
        echo "  ✓ $key_dir"
    else
        echo "  ⚠ $key_dir not found (will be generated by generate-genesis.sh)"
        warnings=$((warnings + 1))
    fi
done

# Check 9: Docker images in compose file
echo ""
echo "Check 9: Docker images referenced"
images=(
    "ghcr.io/unitsnetwork/op-geth"
    "ghcr.io/unitsnetwork/op-reth"
    "sigp/lighthouse"
    "gcr.io/prysmaticlabs/prysm/beacon-chain"
    "python:3.12-slim"
)

for image in "${images[@]}"; do
    if grep -q "$image" docker-compose.yml; then
        echo "  ✓ $image"
    else
        echo "  ✗ $image not found in docker-compose.yml"
        errors=$((errors + 1))
    fi
done

# Check 10: Port mappings
echo ""
echo "Check 10: Port mappings"
ports=(
    "18545:op-geth RPC"
    "28545:op-reth RPC"
    "15052:Lighthouse API"
    "14000:Prysm API"
)

for check in "${ports[@]}"; do
    port=$(echo $check | cut -d: -f1)
    name=$(echo $check | cut -d: -f2)
    if grep -q "$port" docker-compose.yml; then
        echo "  ✓ $name (port $port)"
    else
        echo "  ✗ $name (port $port) not found"
        errors=$((errors + 1))
    fi
done

# Check 11: .gitignore
echo ""
echo "Check 11: .gitignore"
if [ -f ".gitignore" ]; then
    echo "  ✓ .gitignore exists"
    if grep -q "data/" .gitignore && grep -q "logs/" .gitignore; then
        echo "  ✓ data/ and logs/ are ignored"
    else
        echo "  ⚠ data/ or logs/ may not be ignored"
        warnings=$((warnings + 1))
    fi
else
    echo "  ✗ .gitignore not found"
    errors=$((errors + 1))
fi

# Check 12: .env.example
echo ""
echo "Check 12: .env.example"
if [ -f ".env.example" ]; then
    echo "  ✓ .env.example exists"
else
    echo "  ⚠ .env.example not found (optional)"
    warnings=$((warnings + 1))
fi

# Check 13: Network name
echo ""
echo "Check 13: Network configuration"
if grep -q "eth_testnet" docker-compose.yml; then
    echo "  ✓ Network name: eth_testnet"
else
    echo "  ⚠ Network name may not be eth_testnet"
    warnings=$((warnings + 1))
fi

# Check 14: eth_simulateV1 test references
echo ""
echo "Check 14: eth_simulateV1 implementation checks"
if grep -q "eth_simulateV1" tests/test_eth_simulateV1.py; then
    echo "  ✓ Test suite includes eth_simulateV1 tests"
else
    echo "  ✗ eth_simulateV1 tests not found"
    errors=$((errors + 1))
fi

# Final summary
echo ""
echo "====================================================================="
echo "Verification Summary"
echo "====================================================================="
echo "Errors:   $errors"
echo "Warnings: $warnings"
echo ""

if [ $errors -eq 0 ]; then
    echo "✅ SETUP VERIFICATION PASSED"
    echo ""
    echo "Next steps:"
    echo "  1. Run: ./scripts/setup.sh"
    echo "  2. Start: ./scripts/start.sh"
    echo "  3. Check: python3 scripts/health_check.py"
    echo "  4. Test:  python3 tests/test_eth_simulateV1.py"
    exit 0
else
    echo "❌ SETUP VERIFICATION FAILED - $errors error(s) found"
    echo ""
    echo "Please fix the errors above before proceeding."
    exit 1
fi
