PRESET_BASE: minimal
CONFIG_NAME: local-testnet
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 256
MIN_GENESIS_TIME: 1704067200
GENESIS_FORK_VERSION: 0x00000000
GENESIS_DELAY: 10
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32
EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 256
EPOCHS_PER_ETH1_VOTING_PERIOD: 64
SLOTS_PER_HISTORICAL_ROOT: 131072
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
TARGET_COMMITTEE_SIZE: 4
MAX_COMMITTEES_PER_SLOT: 64
MAX_VALIDATORS_PER_COMMITTEE: 2048
BLS_SIGNATURE_BYTE_LENGTH: 96
BYTES_PER_LOGS_BLOOM: 256
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 65536
PROPORTIONAL_SLASHING_MULTIPLIER: 1
MIN_SLASHING_PENALTY_QUOTIENT: 128
WHISTLEBLOWER_REWARD_QUOTIENT: 512
MAX_PROPOSER_SLASHINGS: 16
MAX_ATTESTER_SLASHINGS: 2
MAX_ATTESTATIONS: 128
MAX_DEPOSITS: 16
MAX_VOLUNTARY_EXITS: 16
ALTAIR_FORK_VERSION: 0x01000000
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x02000000
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x03000000
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x04000000
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_VERSION: 0x05000000
ELECTRA_FORK_EPOCH: 18446744073709551615
DOMAIN_BEACON_PROPOSER: 0x00000000
DOMAIN_BEACON_ATTESTER: 0x01000000
DOMAIN_RANDAO: 0x02000000
DOMAIN_DEPOSIT: 0x03000000
DOMAIN_VOLUNTARY_EXIT: 0x04000000
DOMAIN_SELECTION_PROOF: 0x05000000
DOMAIN_AGGREGATE_AND_PROOF: 0x06000000
DOMAIN_SYNC_COMMITTEE: 0x07000000
DOMAIN_SYNC_COMMITTEE_SELECTION_PROOF: 0x08000000
DOMAIN_CONTRIBUTION_AND_PROOF: 0x09000000
INACTIVITY_SCORE_BIAS: 16777216
INACTIVITY_SCORE_RECOVERY_RATE: 167772
MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR: 2048
PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR: 2
SYNC_COMMITTEE_SIZE: 512
MIN_SYNC_COMMITTEE_PARTICIPANTS: 1
MIN_EPOCHS_TO_INACTIVITY_PENALTY: 4
DOWNWARD_THRESHOLD: 1
UPWARD_THRESHOLD: 1024
BONUS_BASE_FACTOR: 64
BONUS_REWARD_NUMERATOR: 3
BONUS_REWARD_DENOMINATOR: 5
INACTIVITY_PENALTY_QUOTIENT: 50331648
INACTIVITY_PENALTY_QUOTIENT_ALTAIR: 67108864
BASE_REWARD_FACTOR: 64
BASE_REWARD_PER_INCREMENT: 1099511627776
INACTIVITY_PENALTY_QUOTIENT_BELLATRIX: 50331648
MIN_SLASHING_PENALTY_QUOTIENT_BELLATRIX: 128
PROPORTIONAL_SLASHING_MULTIPLIER_BELLATRIX: 3
SYNC_COMMITTEE_SUBNET_COUNT: 4
TARGET_EPOCHS_TO_BLOB_PROPOSAL: 2
MAX_BLOB_GAS_PER_BLOCK: 393216
BLOB_TX_GAS_PER_BLOB: 131072
MIN_GAS_PRICE_BLOB_TX: 1
MAX_REQUEST_BLOCKS_DENOMINATOR: 128
MAX_REQUEST_BLOCKS_SIDECAR: 64
MAX_WITHDRAWALS_PER_PAYLOAD: 16
FULL_VALIDATOR_WITHDRAWAL_DELAY: 256
MAX_REQUEST_BLOB_SIDECARS: 768
DEPOSIT_CHAIN_ID: 1337
DEPOSIT_NETWORK_ID: 1337
DEPOSIT_CONTRACT_ADDRESS: 0x0000000000000000000000000000000000006A7e
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0
